steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "builds"
      - "submit"
      - "."
      - "--pack=image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-d\
        eploy/frontend-service:latest"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "frontend-service"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy\
        /frontend-service:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
options:
  logging: CLOUD_LOGGING_ONLY
